### ISSUE TITLE
can I get same benefits if I use ngrx?

### ISSUE THREAD

**Issue by xmlking** [DeborahK/Angular-RxJS#1]
@DeborahK I watched your presentation on youtube and it was a great inspiration for me, to use  **combineLatest** and **shareReplay**  for `caching` and efficient `Change Detection` .
I am thinking of I use redux store implementations like `ngrx` or `ngxs`, I can get same benefits?

**Comment by DeborahK** [comment]
Redux implementations such as `ngrx` and `ngxs` are state management libraries. You can do state management with RxJS (and some of `ngrx` and `ngxs` leverage RxJS). But RxJS is much more.
