### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by MattBowden** [DeborahK/Angular-RxJS#18]
When clicking the 'Refresh Data' button we receive - TypeError: Cannot read property 'filter' of undefined, in the following scenario:

In APM-WithExtras in product-list.component.html uncomment the 'Refresh Data' button and in product.service.ts replace the this.products$ observable with this.products2$ in the combineLatest operator for the productsWithCategory$ property like so:

`productsWithCategory$ = combineLatest([
    this.products2$,
    this.productCategoryService.productCategories$
  ]).pipe(
    map(([products, categories]) =>
      products.map(product => ({
        ...product,
        price: product.price * 1.5,
        category: categories.find(c => product.categoryId === c.id).name,
        searchKey: [product.productName]
      }) as Product)
    ),
    shareReplay(1)
  );`

The error is being thrown in product-list.component.ts on the products$ property due to the this.productService.productsWithCRUD$ observable being undefined following the scan operation.

**Comment by DeborahK** [comment]
Yeah, it's hard to have one repo try to show lots of different techniques. It's not feasible to uncomment some of these techniques and have them easily work with everything else. :-(

The `productsWithCRUD$` makes the assumption that once the products are retrieved, the only emitted values are for a "modified" action and it adds/updates/deletes a product. On a refresh, that code is re-executed with no modified product and hence the `filter` of undefined message.

You'd need to modify `productsWithCRUD$` to make it smarter and only perform the scan if it indeed has a modified action.

I didn't fully test this, but something like this would work:

```
  productsWithCRUD$ = merge(
    this.productsWithCategory$,
    this.productModifiedAction$
      .pipe(
        concatMap(product => this.saveProduct(product)),
      ))
    .pipe(
      scan((products: Product[], product: Product) => {
        if (product instanceof Array) {
          return product;
        } else {
          return this.modifyProducts(products, product);
        }
      }),
      shareReplay(1)
    );
```

**Comment by MattBowden** [comment]
Many thanks for you speedy reply, your proposed solution worked in all my test scenarios.
I thought there might've been an Rxjs operator to use instead of merge, that when this.productsWithCategory$ received a new value through the stream it could seed the scan operator thus acting as it does on page load when the HTTP call is made but no CRUD action is performed, however I couldn't find anything suitable in the myriad of Rxjs operators.
