### ISSUE TITLE
230 high severity vulnerabilities

### ISSUE THREAD

**Issue by kdawg1406** [DeborahK/Angular-RxJS#3]
There are 230 high severity vulnerabilities in this version of the repo.  See image.  

After running: npm install, I ran npm audit fix, and they all went away.  Recommend running and pushing the solution back into source.  Best to you, Karl

![2019-09-26_15-39-22](https://user-images.githubusercontent.com/5623887/65719532-fc48c880-e073-11e9-8c59-98bba4a64fce.png)

**Comment by DeborahK** [comment]
Thanks, Karl! 

I removed the lock files. That should ensure that the packages are updated when installing.

Let me know if that resolves this issue.

Thanks again!
