### ISSUE TITLE
Question: Why comment out the 'isLoading' subject from product.service?

### ISSUE THREAD

**Issue by guillermoarellano** [DeborahK/Angular-RxJS#4]
Hi Deborah,

I think the is loading observable makes sense to have in the service. It allows my  component to be leaner. Was there a bug that I haven't experienced yet? 

Thanks,
Guillermo

**Comment by DeborahK** [comment]
I only commented it out because I was trying to simplify the `switchMap/forkJoin` example for those that are just learning these techniques.

What I should probably do is add a `selectedProductSuppliers4$ that has this code. :-)

**Comment by DeborahK** [comment]
Done!
