### ISSUE TITLE
Where is place for business validation in reactive development?

### ISSUE THREAD

**Issue by dewebeloper** [DeborahK/Angular-RxJS#80]
@DeborahK I sow your presentation on Angular conf and got interested for reactive development.
My question is, where is place for business validation for model that should be post to database. Business validation may depend on other parameters besides the model itself.
What would be approach/pattern for this case?

**Comment by DeborahK** [comment]
It really depends on the type of validation and the application requirements.

Some of the basic field-level validation could be in the component and executed immediately so the user knows that their entry isn't correct or isn't within the specifications.

Some of the validation could be in the service, especially if that validation is across components.

The validation must always be repeated in the backend server. No matter how good the validation is in the client, there are always ways to bypass that validation. So it's a good idea to always have the final set of validation on the backend, just before the actual save.
